### ISSUE TITLE
Home Page: Add social media icons

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#73]

**Comment by cauverysm** [comment]
![social-media-icons](https://cloud.githubusercontent.com/assets/18243080/22403213/809ad00a-e636-11e6-95ca-47fda65204a7.png)
updated the html to horizontal display of icons (previously was vertical and had unnecessary spacing[per the materialize css] in the dropdown items)

**Comment by politologu** [comment]
I think is not good to put on the top the social media, at the bottom need to put :)  or the footer

**Comment by jxwang16** [comment]
1. The material icon library is quite large. Try to find out a way to reference the icons through URL instead of download the whole library.
2. Angular Material module is not able to be installed automatically from systemjs. Receiving error: app/app.module.ts(8,32): error TS2307: Cannot find module '@angular/material'.
3. Move the social icons to the bottom of the page

**Comment by politologu** [comment]
now is ok Move the social icons to the bottom of the page
